### PR TITLE
Update to 3.7.8

### PR DESCRIPTION
**Pull request by harrison-caudill**
Update our fork to 3.7.8 in master, and update the build scripts to work readily with both 12.04 as well as 15.10 with a multi-threaded build.

@jtrutna - Primary Review
@JoelSpark - FYI

### CODE REVIEW

**Comment by harrison-caudill** [comment]
@JoelSpark @jtrutna bump

**Comment by JoelSpark** [comment]
@harrison-caudill before merging this, could we make a docker using 3.7.8 and run some contacts with it, make sure we're not breaking anything in production?

**Comment by harrison-caudill** [comment]
@JoelSpark yes, there will be a rollout procedure.  Especially since this rollout will affect the uhf infrastructure as well.

**Comment by harrison-caudill** [comment]
@jtrutna @JoelSpark The .deb built from this branch has now been through tests, and has now seen a few days in production without any ill effects.

Mind if we get this merged in so that we can officially roll out a build from master?

**Comment by jtrutna** [comment]
Too many files in diff. 8O  Could we get some more context on what is being changed here?  We're merging from upstream?  gist of a diff then?

**Comment by harrison-caudill** [comment]
@jtrutna This branch is pulling from upstream's 3.7.8 release.  It is also updating our internal build-scripts to work with the new code, and also to build in parallel on both 12.04 and 15.10 so we have dev and release builds of our .deb files.

Diff of upstream/v3.7.8 vs this branch: https://github.com/gnuradio/gnuradio/compare/gnuradio:v3.7.8...nsat:kungfoo-378

**Pull request merged**
